preprocess voice data by mfcc. learn is prediced as stop. tflite_convert --keras_model_file best_model.hdf5 --output_file best_model.tflite can't reduce MFCC_SIZE down to 256 because of following error.
/home/caz/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1618   try:
-> 1619     c_op = c_api.TF_FinishOperation(op_desc)
   1620   except errors.InvalidArgumentError as e:

InvalidArgumentError: Negative dimension size caused by subtracting 7 from 5 for 'conv1d_4/convolution' (op: 'Conv2D') with input shapes: [?,1,5,32], [1,7,32,64].